# Generated by Django 5.0.2 on 2024-02-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('coffee', models.CharField(max_length=100)),
                ('syrup', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_of_milk', models.IntegerField(null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
